---
name: bilibili-live-tools

"on":
  push:
    branches:
      - 'master'

jobs:
  docker:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
        with:
          repository: 'Dawnnnnnn/bilibili-live-tools'
          path: 'bilibili-live-tools'

      - uses: docker/setup-buildx-action@v2

      - uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - uses: docker/build-push-action@v4
        with:
          push: true

          tags: |
            vergedx/bilibili-live-tools:v0.0.1
            ghcr.io/vanilla-s-lab/bilibili-live-tools:v0.0.1

          context: ./bilibili-live-tools
